### ISSUE TITLE
How about non-angular version or iOS version?

### ISSUE THREAD

**Issue by c1ngular** [kazemihabib/nativescript-vlc-player#1]
Just wondering ~Not really an issue , thanks!

**Comment by kazemihabib** [comment]
well,currently I'm developing an android project with this plugin after finishing that , I will start ios version and port android app to ios and maybe the non angular version 😀

**Comment by c1ngular** [comment]
@kazemihabib wonderful , thanks, can't Wait to try it out , learning from your process as well !

**Comment by jibon57** [comment]
@kazemihabib any update for ios please?

**Comment by kazemihabib** [comment]
no, I didn't start the ios version yet .

**Comment by jibon57** [comment]
@kazemihabib, Any possibility to get it for IOS?

**Comment by kazemihabib** [comment]
Sorry, but I will not support this plugin because I'm not using nativescript anymore.
